export const FETCH_ISSUES_REQUEST = 'FETCH_ISSUES_REQUEST';
export const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export const FETCH_ISSUES_FAILURE = 'FETCH_ISSUES_FAILURE';

export const FETCH_REPOINFO_REQUEST = 'FETCH_REPOINFO_REQUEST';
export const FETCH_REPOINFO_SUCCESS = 'FETCH_REPOINFO_SUCCESS';
export const FETCH_REPOINFO_FAILURE = 'FETCH_REPOINFO_FAILURE';



export const INCREAMENT_WATCH="INCREAMENT_WATCH";
export const INCREAMENT_STAR="INCREAMENT_STAR";
export const INCREAMENT_FORK="INCREAMENT_FORK"
